name: "my-action"
description: "AKS common setup step before deploy yaml file"

on:
  workflow_dispatch:
    inputs:
      kube_cluster:
        description: 'Please select your cluster'
        required: true
        default: "myAKSCluster-sg"

      resource_group:
        description: 'Please enter your resource group'
        required: true
        default: "myResourceGroup"
        
      runs_on:
        description: 'Please enter your runner'
        required: true
        default: "ubuntu-latest"
runs:
  using: "composite"
  steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}'
          cluster-name: ${{ inputs.kube_cluster }}
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
