name: Dispatch Event Source

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Dispatch Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_REPO_TOKEN }}
          repository: kunlawitauttra/hello-world-composite-action
          event-type: my-custom-event
          client-payload: '{"key1": "dispatch-value1", "key2": "dispatch-value2"}'








