name: my-reuseable

on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: true
        default: ubuntu-latest
        type: string
      KUBE_CLUSTER:
        required: true
        type: string
      REGISTRY:
        required: true
        type: string
      IMAGE:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ inputs.REGISTRY }}
          repository: ${{ secrets.repository }}
          image:  myapp
          folder: django/myproject
          branch: master
          tag: ${{ github.sha }}
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}'
          cluster-name: ${{ inputs.KUBE_CLUSTER }}
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
             ${{ inputs.IMAGE }}.yaml
          images: '${{ inputs.REGISTRY }}.azurecr.io/${{ secrets.repository }}/myapp:${{ github.sha }}'
          pull-images: false
