name: my-reuse
on:
  repository_dispatch:
    inputs:
      RUNS_ON:
        required: true
        default: ubuntu-latest
        type: string
      KUBE_CLUSTER:
        required: true
        default: myAKSCluster-sg
        type: string
      REGISTRY:
        required: true
        default: kunlawit26acr
        type: string
jobs:
  call-workflow-deploy-microservice:
    uses: ./.github/workflows/my-reuseable.yml
    with:
      RUNS_ON: ${{ inputs.RUNS_ON }}
      KUBE_CLUSTER: ${{ inputs.KUBE_CLUSTER }}
      REGISTRY: ${{ inputs.REGISTRY }}
    secrets: inherit
