name: my-reuse
on:
  workflow_dispatch:
    inputs:
      RUNS_ON:
        description: RUNS_ON
        required: true
        default: ubuntu-latest
        type: string
      KUBE_CLUSTER:
        description: KUBE_CLUSTER
        required: true
        default: myAKSCluster-sg
        type: string
      REGISTRY:
        description: REGISTRY
        required: true
        default: kunlawit26acr
        type: string
      APP:
        description: APP
        required: true
        default: myapp
        type: string
jobs:
  call-workflow-deploy-microservice:
    uses: ./.github/workflows/my-reuseable.yml
    with:
      RUNS_ON: ${{ inputs.RUNS_ON }}
      KUBE_CLUSTER: ${{ inputs.KUBE_CLUSTER }}
      REGISTRY: ${{ inputs.REGISTRY }}
      APP: ${{ inputs.APP }}
    secrets: inherit
