name: my-workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

  call-workflow-local-repo:
    uses: ./.github/workflows/reuseable-workflow01.yml
    with:
      node: 8
