name: _reusable-common-deploy

on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: true
        type: string
      CLUSTER_NAME:
        required: true
        type: string
jobs:
  deploy-common:
    name: Deploy Common
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Checkout pipelines
        uses: actions/checkout@v3

      - name: "Common Setup"
        uses: ./.github/workflows/action.yml
        with:
          CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }} 
